[package]
name = "derive-graph-elem"
version = "0.1.0"
authors = ["Jamie Blondin <jblondin@gmail.com>"]

description = "Cusrom derive macro to generate Rhubarb graph elements."

[lib]
proc-macro = true

[dependencies]
syn = "0.14"
quote = "0.6"
proc-macro2 = "0.4"
